
CREATE OR REPLACE TRIGGER insert_new_pay
    BEFORE INSERT ON PAY
    REFERENCING NEW AS new_row
    FOR EACH ROW
BEGIN
    UPDATE PAY SET SALARY = (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEES.EMPLOYEE_ID = :new_row.EMPLOYEE_ID),
                   COMMISSION_PCT = (SELECT COMMISSION_PCT FROM EMPLOYEES WHERE EMPLOYEES.EMPLOYEE_ID = :new_row.EMPLOYEE_ID)
    WHERE CARDNR = :new_row.CARDNR;
END;




