
-- CHANGE DEPARTMENT AMOUNT IN LOCATION
-- CREATE OR REPLACE TRIGGER department_amount_update
--     BEFORE INSERT OR DELETE ON DEPARTMENTS
--     FOR EACH ROW
-- BEGIN
--     CASE
--         WHEN INSERTING THEN
--             UPDATE LOCATIONS SET DEPARTMENT_AMOUNT = DEPARTMENT_AMOUNT + 1 WHERE LOCATION_ID = :NEW.LOCATION_ID;
--         WHEN DELETING THEN
--             UPDATE LOCATIONS SET DEPARTMENT_AMOUNT = DEPARTMENT_AMOUNT - 1 WHERE LOCATION_ID = :OLD.LOCATION_ID;
--     END CASE;
-- END;


--INSERT ROW IN employment_log TABLE
CREATE OR REPLACE TRIGGER employers_hiring_firing
    AFTER INSERT OR DELETE ON EMPLOYEES
    FOR EACH ROW
BEGIN
    CASE
    WHEN INSERTING THEN
        add_employment_log('HIRED', :NEW.FIRST_NAME, :NEW.LAST_NAME);
    WHEN DELETING THEN
        add_employment_log('FIRED', :OLD.FIRST_NAME, :OLD.LAST_NAME);
    END CASE;
END;



